default_platform(:android)

platform :android do
  desc "Build With Firebase App Distribution And Fastlane"
  lane :Android_Distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    firebase_app_distribution(
      app: ENV['APP_ID'],
      testers: "adelaboali82@gmail.com",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/apk/production/release/app-production-release.apk",
      release_notes: "SadioZmano"
    )
  end
end

